id: P004267
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00KG03653
  title: འདས་ལོག་ཀརྨ་དབང་འཛིན་གྱི་རྣམ་ཐར་ཐར་པའི་ལྕགས་ཀྱུ།
  author: ''
  volumes:
    cbf95e205b49454cb0089f17ae6f9e50:
      image_group_id: I00KG03733
      title: ''
      volume_number: 1
      total_pages: 142
      base_file: v001.txt
